import type { InvitationTemplate } from "./types";

export const invitationTemplates: InvitationTemplate[] = [
  {
    id: "wedding-classic-gold",
    category: "wedding",
    name: "זהב קלאסי",
    description: "טיפוגרפיה אלגנטית, מסגרת עדינה וגימור זהב.",
    isPremium: true,
    preview: {
      gradient: "from-amber-950/90 via-stone-900 to-rose-950",
      overlay: "from-amber-200/10 via-transparent to-rose-300/10",
      accent: "text-amber-200/90",
      ornament: "floral",
      sampleTitle: "שרה & דוד",
      sampleSubtitle: "שמחים להזמינכם לחתונתנו",
    },
  },
  {
    id: "wedding-blush-garden",
    category: "wedding",
    name: "גן ורוד",
    description: "פרחוני רך, פלטת ורודים וקרם לאירוע חלומי.",
    isPremium: true,
    preview: {
      gradient: "from-rose-900/80 via-fuchsia-950 to-violet-950",
      overlay: "from-rose-200/15 via-transparent to-pink-100/5",
      accent: "text-rose-200/90",
      ornament: "elegant",
      sampleTitle: "מיה & אור",
      sampleSubtitle: "נשמח לחגוג איתכם",
    },
  },
  {
    id: "birthday-confetti",
    category: "birthday",
    name: "קונפטי שמח",
    description: "צבעים עזים, אנרגיה גבוהה ומראה חגיגי.",
    isPremium: false,
    preview: {
      gradient: "from-orange-900 via-amber-950 to-yellow-950",
      overlay: "from-amber-300/20 via-transparent to-pink-400/10",
      accent: "text-amber-200",
      ornament: "confetti",
      sampleTitle: "יום הולדת 30",
      sampleSubtitle: "בואו לחגוג איתי!",
    },
  },
  {
    id: "birthday-neon-night",
    category: "birthday",
    name: "לילה ניאון",
    description: "ניאון מודרני וסגנון מסיבת לילה עכשווי.",
    isPremium: true,
    preview: {
      gradient: "from-violet-950 via-fuchsia-950 to-indigo-950",
      overlay: "from-cyan-400/10 via-fuchsia-400/10 to-transparent",
      accent: "text-fuchsia-200",
      ornament: "celebration",
      sampleTitle: "מסיבת הפתעה",
      sampleSubtitle: "הצטרפו לערב בלתי נשכח",
    },
  },
  {
    id: "bar-mitzvah-jerusalem",
    category: "bar-mitzvah",
    name: "ירושלים עתיקה",
    description: "מוטיבים מסורתיים, עברית מרכזית ואווירה חגיגית.",
    isPremium: true,
    preview: {
      gradient: "from-blue-950 via-indigo-950 to-slate-950",
      overlay: "from-sky-300/10 via-transparent to-amber-200/10",
      accent: "text-sky-200",
      ornament: "torah",
      sampleTitle: "בר מצווה",
      sampleSubtitle: "ליאור בן משה",
    },
  },
  {
    id: "bar-mitzvah-modern-blue",
    category: "bar-mitzvah",
    name: "כחול מודרני",
    description: "קווים נקיים, דו-לשוני ועיצוב עכשווי.",
    isPremium: false,
    preview: {
      gradient: "from-slate-900 via-blue-950 to-indigo-950",
      overlay: "from-blue-300/10 via-transparent to-violet-300/10",
      accent: "text-blue-200",
      ornament: "minimal",
      sampleTitle: "Bat Mitzvah",
      sampleSubtitle: "נועה בת יעקב",
    },
  },
  {
    id: "business-minimal-black",
    category: "business",
    name: "מינימל שחור",
    description: "מונוכרום מלוטש למותגים ואירועי VIP.",
    isPremium: true,
    preview: {
      gradient: "from-zinc-950 via-neutral-950 to-stone-950",
      overlay: "from-white/5 via-transparent to-zinc-400/10",
      accent: "text-zinc-300",
      ornament: "minimal",
      sampleTitle: "השקת מוצר",
      sampleSubtitle: "TechFlow · 2026",
    },
  },
  {
    id: "business-gala-premium",
    category: "business",
    name: "גאלה פרימיום",
    description: "זהב ושחור, מתאים לכנסים וערבי גאלה.",
    isPremium: true,
    preview: {
      gradient: "from-stone-950 via-zinc-900 to-amber-950",
      overlay: "from-amber-300/10 via-transparent to-amber-500/5",
      accent: "text-amber-200/80",
      ornament: "elegant",
      sampleTitle: "ערב גאלה",
      sampleSubtitle: "חברת אלפא · הזמנה אישית",
    },
  },
];
